import NavBar from "@/components/Navbar/NavBar";
import NavItem from "@/components/Navbar/NavItem";
import { NAVCOMPONENTS } from "@/constants/components";
import { PageStoreProvider } from "@/providers/createPageStore";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Your app",
  description: "Generated by create next app",
};

const CanvasLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <PageStoreProvider>
      <div className=''>
        <NavBar />
        {children}
      </div>
    </PageStoreProvider>
  );
};

export default CanvasLayout;
