import NavItem from "@/components/Navbar/NavItem";
import { NAVCOMPONENTS } from "@/constants/components";
import { PageStoreProvider } from "@/providers/createPageStore";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Your app",
  description: "Generated by create next app",
};

const CanvasLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <PageStoreProvider>
      <div className='bg-gray-300 h-full'>
        {/* <aside className='max-w-3xs w-3xs'>
          {NAVCOMPONENTS.map((component) => (
            <div key={component.id} className='flex items-center'>
              <NavItem component={component} />
            </div>
          ))}
        </aside> */}
        {children}
      </div>
    </PageStoreProvider>
  );
};

export default CanvasLayout;
